language: python

python:
  - 3.8

before_install:
  - python --version
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install codecov

script: pytest --cov

after_success:
  - codecov